FROM alpine:3.7

RUN apk update && apk upgrade
RUN curl -O https://dl.grafana.com/enterprise/release/grafana-enterprise-7.5.7.darwin-amd64.tar.gz
RUN tar -zxvf grafana-enterprise-7.5.7.darwin-amd64.tar.gz

