apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: main-claster
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: grafana-lbl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-lbl
  template:
    metadata:
      labels:
        app: grafana-lbl
    spec:
      containers:
        - image: grafana_image
          imagePullPolicy: Never
          name: grafana
          ports:
            - containerPort: 3000
